name: ACR Build and Push

on:
  push:
    branches:
      - master

env:
  ACR_REGISTRY: devaksclusterregistry.azurecr.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build and Test
        run: ./mvnw clean package

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.ACR_REGISTRY }}/hello-world-app:v1.0

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          loginServer: ${{ env.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}