name: Push docker image to ACR

on:
  push:
    branches:
      - main

env:
  AZURE_REGISTRY: devaksclusterregistry.azurecr.io
  IMAGE_TAG: ${{ env.TAG_NAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build and test code
        run: ./mvnw clean package

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.AZURE_REGISTRY }}/spring-boot-app:${{ env.IMAGE_TAG }}

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          loginServer: ${{ env.AZURE_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}